### ISSUE TITLE
Amazon scraper fails to log in

### ISSUE THREAD

**Issue by mikebryant** [jbms/finance-dl#24] opened 2019-12-02 17:38 UTC
When I try to use the amazon scraper, amazon presents me with just the email text box, with a `Continue` button.

Once I click that, the scraper works, as it can then find the password.

It might be nice for it to automatically click on the Continue button if there is one?

**Comment by bayesianmind** [comment] 2021-03-20 22:30
Amazon is often changing this screen. Some folks fixed this a while back but it breaks regularly.

**Comment by vkurup** [comment] 2021-03-20 22:38
FWIW, I started using beancount and this repo about a month ago and I have been successfully using the fixes in [this branch](https://github.com/jbms/finance-dl/pull/38), which was just recently merged. So at least for now, I think this bug can be closed. Unless of course the OP is still having issues, in which case an updated set of steps to reproduce the issue would be useful.

**Comment by Zburatorul** [comment] 2021-10-10 17:45
Closing due to inactivity and because sounds like fixed.

**Closed as completed by Zburatorul** 2021-10-10 17:45 UTC
